### ISSUE TITLE
iOS 10

### ISSUE THREAD

**Issue by azeroth12** [AppDaemon/appdaemon#1335]
I have appdaemon set to autoupdate on my docker server. After it went to 4.1.0 today it no longer works with my older iOS 10 wall mounted iPad. Is this by design and I need to downgrade and peg my appdaemon instance? Or is this a bug? I kinda of think that older tablets are a huge consumer of the dashboard part of appdaemon.

**Comment by azeroth12** [comment]
Reverting to 4.0.8 put me back in business.

**Comment by frenck** [comment]
Not going to explain or discuss this, but... #1140

**Comment by acockburn** [comment]
Thanks for catching that @frenck

**Comment by sdt-ryan** [comment]
Gotcha so we're in dependency hell here... Guessing bumping JS Socket.IO would be too easy an answer...

**Comment by azeroth12** [comment]
Gotcha so we're in dependency hell here... Guessing bumping JS Socket.IO would be too easy an answer...

**Comment by acockburn** [comment]
Might work - it’a basically a static library I included with AD so it looks like it just needs updating

**Comment by acockburn** [comment]
Fixed in dev

**Comment by boojew** [comment]
Should it work w/ the docker dev image? I tested and it didnt work for me

**Comment by Odianosen25** [comment]
@boojew,

So you running the latest dev and still not working?

**Comment by boojew** [comment]
Correct. I am using acockburn/appdaemon:dev

**Comment by miraculixdruid** [comment]
https://github.com/hassio-addons/addon-appdaemon/issues/156

**Comment by chiefcomm** [comment]
is there a likely hood this issue will be resolved any time soon? This is affecting a huge user base of people using older iPads (and other tablets). @frenck already explained the cause on August 23rd which is linked to https://github.com/AppDaemon/appdaemon/issues/1348 and the same as previous issue https://github.com/AppDaemon/appdaemon/issues/1140.

**Comment by acockburn** [comment]
As I said in the other issue for this - I have no way to test it so I am reliant on someone figuring this out. I have tried twice so far to fix it with no luck and I don't know what to try next.

**Comment by frenck** [comment]
This can be tested on any system, by anyone, by setting:

```yaml
http: 
  transport: socketio
```

**Comment by acockburn** [comment]
And it works just fine on my iPads but breaks on older iPads apparently

**Comment by acockburn** [comment]
Thanks to a PR submitted by @clyra this should be fixed in dev

**Comment by rvnijnatten** [comment]
Hi @acockburn, can you possibly give us an eta on the release that contains this fix? Thanks

**Comment by ReneTode** [comment]
if you dont want to wait, then copy the directory basejavascript from github appdaemon/widgets to your config area (from appdaemon) in 'config_area'/custom_widgets

that will most likely solve the case untill next release.

**Comment by safadig** [comment]
copy content of directory appdaemon/appdaemon/widgets/basejavascript/ from github to HA /config/appdaemon/custom_widgets/basejavascript
create /basejavascript as most likely it is not in custom_widgets

**Comment by auckz** [comment]
Tried this fix but can't get to work on the original iPad Mini running 9.3.5

**Comment by ReneTode** [comment]
i dont know how you tried.
maybe you can come to our discord and we can help you.

**Comment by chiefcomm** [comment]
I found that the process documented in this post helped me a lot and it works on a iPad Mini running 9.3.5 https://github.com/hassio-addons/addon-appdaemon/issues/156#issuecomment-939275413

**Comment by auckz** [comment]
> i dont know how you tried. maybe you can come to our discord and we can help you.

I copied the whole basejavascript folder to my config/appdaemon/custom_widgets/basejavascript
I'm still having the same blank buttons

I'll hop on discord and see if we can sort this out, maybe I'm missing something

**Comment by azeroth12** [comment]
As an fyi I was lazy and just pulled the :dev branch into docker and all is well again. So the fixes do work just haven’t been released. Nothing mission critical here so don’t mind it for now. I’m sure renetode’s suggestion would have the same effect minus the risk.
