### ISSUE TITLE
The client is using an unsupported version of the Socket.IO or Engine.IO

### ISSUE THREAD

**Issue by juan11perez** [AppDaemon/appdaemon#1348]
The above error is back. 
Recommended action on this [site](https://stackoverflow.com/questions/66069215/the-client-is-using-an-unsupported-version-of-the-socket-io-or-engine-io-protoco) fixed it.

`pip install --upgrade python-socketio==4.6.0
pip install --upgrade python-engineio==3.13.2
pip install --upgrade Flask-SocketIO==4.3.1`

**Comment by acockburn** [comment]
Fixed in dev

**Comment by teqali** [comment]
when will it be fix?

**Comment by miraculixdruid** [comment]
https://github.com/hassio-addons/addon-appdaemon/issues/156

**Comment by chiefcomm** [comment]
When is this going to be fixed, 4.1.0 has crippled anyone using older displays (of which is a large proportion of the user base).

**Comment by acockburn** [comment]
I have no idea - I don’t know what the problem is nor do I have any way to test it. If anyone can help me figure it out I’m happy to make the fix. In the meantime I suggest you downgrade to the last working version of appdaemon.

**Comment by chiefcomm** [comment]
> I have no idea - I don’t know what the problem is nor do I have any way to test it. If anyone can help me figure it out I’m happy to make the fix. In the meantime I suggest you downgrade to the last working version of appdaemon.

Issue is a duplicate of #1335 @frenck explained the issue and the fix

**Comment by acockburn** [comment]
thanks to a PR by @clyra this should be fixed in dev now

**Comment by NicolasSenetLarson** [comment]
I'm still getting this error on AppDaemon 4.2.1.
Is there a reason that appdaemon/appdaemon/assets/javascript/socket.io.js is kept at version 2.1.1?

**Comment by acockburn** [comment]
AT this point I am pretty much dropping support for older iPads, unless someone can come up with a PR to fix it - I don't have the means to test it.
