### ISSUE TITLE
AttributeError: property 'global_vars' of 'StatusNotifier' object has no setter

### ISSUE THREAD

**Issue by dekiesel** [AppDaemon/appdaemon#2314]
### What happened?

Encountering this after updating to 4.5.4. `global_vars` is an app. It works as it should in 4.4.2

### Version

4.5.4

### Installation type

Docker container

### Relevant log output

```sh
2025-05-30 10:55:48.809636 WARNING AppDaemon: App 'stat_notifier_mys_4' failed to start
2025-05-30 10:55:48.810134 ERROR Error: =====  Failed to start 'stat_notifier_mys_4'  =============================
2025-05-30 10:55:48.810389 ERROR Error: AppStartFailure: App 'stat_notifier_mys_4' failed to start
2025-05-30 10:55:48.810855 ERROR Error:   InitializationFail: initialize() method failed for app 'stat_notifier_mys_4'
2025-05-30 10:55:48.811457 ERROR Error:     AttributeError: property 'global_vars' of 'StatusNotifier' object has no setter
2025-05-30 10:55:48.812146 ERROR Error:       File "/usr/local/lib/python3.12/site-packages/appdaemon/app_management.py", line 392, in start_app
2025-05-30 10:55:48.812342 ERROR Error:         await self.initialize_app(app_name)
2025-05-30 10:55:48.812509 ERROR Error:       File "/usr/local/lib/python3.12/site-packages/appdaemon/app_management.py", line 289, in initialize_app
2025-05-30 10:55:48.812667 ERROR Error:         await utils.run_in_executor(self, init_func)
2025-05-30 10:55:48.812884 ERROR Error:       File "/usr/local/lib/python3.12/site-packages/appdaemon/utils.py", line 554, in run_in_executor
2025-05-30 10:55:48.813036 ERROR Error:         return await future
2025-05-30 10:55:48.813189 ERROR Error:                ^^^^^^^^^^^^
2025-05-30 10:55:48.813337 ERROR Error:       File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
2025-05-30 10:55:48.813495 ERROR Error:         result = self.fn(*self.args, **self.kwargs)
2025-05-30 10:55:48.813706 ERROR Error:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-30 10:55:48.813858 ERROR Error:       File "/conf/apps/status_notifier/status_notifier.py", line 12, in initialize
2025-05-30 10:55:48.814009 ERROR Error:         self.global_vars = self.get_app('global_vars')
2025-05-30 10:55:48.814159 ERROR Error:         ^^^^^^^^^^^^^^^^
2025-05-30 10:55:48.814325 ERROR Error: ===========================================================================
```

### Relevant code in the app or config file that caused the issue

```sh
`status_notifier.py` initialize function:

class StatusNotifier(hass.Hass):

    def initialize(self):
        self.listen_state_handle_list = []
        self.listen_event_handle_list = []

        self.global_vars = self.get_app('global_vars')
        self.notifier = self.get_app('notifier')

        self.debug_mode = globals.get_arg(self.args, "DEBUG")
        self.entity_name = globals.get_arg(self.args, "entity_name")
        self.entity = globals.get_arg(self.args, "entity")
        self.threshold = int(globals.get_arg(self.args, "threshold"))
        self.when = globals.get_arg(self.args, "when")
        self.notification_method = globals.get_arg(self.args, "notification_method")
        self.recipient = globals.get_arg(self.args, "recipient")
        self.message = globals.get_arg(self.args, "message")
        self.notification_sent = False

        self.listen_state_handle_list.append(
            self.listen_state(self.notify_state, self.entity)
        )
```

**Comment by acockburn** [comment]
Thanks for reporting we will take a look

**Comment by jsl12** [comment]
I added a setter for that property, so doing it the way you were before should work again.

However, with the new app management system, you could just have a `globals.py` and import things directly from it. AppDaemon now understands when files import each other, and takes this into account for the automatic reloading.

**Comment by acockburn** [comment]
The fix for this will be available in 4.5.6

**Comment by dekiesel** [comment]
I'll rewrite my apps to use globals.py, but just fyi, the fix isn't working in 4.5.8:

```
2025-06-04 15:04:03.708712 INFO AppDaemon: Calling initialize() for stat_notifier_mys_4
2025-06-04 15:04:03.710151 WARNING AppDaemon: App 'stat_notifier_mys_4' failed to start
2025-06-04 15:04:03.710593 ERROR Error: =====  Failed to start 'stat_notifier_mys_4'  =============================
2025-06-04 15:04:03.710740 ERROR Error: AppStartFailure: App 'stat_notifier_mys_4' failed to start
2025-06-04 15:04:03.711157 ERROR Error:   InitializationFail: initialize() method failed for app 'stat_notifier_mys_4'
2025-06-04 15:04:03.711640 ERROR Error:     AttributeError: property 'global_vars' of 'StatusNotifier' object has no setter
2025-06-04 15:04:03.712232 ERROR Error:       File "/usr/local/lib/python3.12/site-packages/appdaemon/app_management.py", line 392, in start_app
2025-06-04 15:04:03.712477 ERROR Error:         await self.initialize_app(app_name)
2025-06-04 15:04:03.712618 ERROR Error:       File "/usr/local/lib/python3.12/site-packages/appdaemon/app_management.py", line 289, in initialize_app
2025-06-04 15:04:03.712742 ERROR Error:         await utils.run_in_executor(self, init_func)
2025-06-04 15:04:03.712872 ERROR Error:       File "/usr/local/lib/python3.12/site-packages/appdaemon/utils.py", line 559, in run_in_executor
2025-06-04 15:04:03.713000 ERROR Error:         return await future
2025-06-04 15:04:03.713129 ERROR Error:                ^^^^^^^^^^^^
2025-06-04 15:04:03.713282 ERROR Error:       File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
2025-06-04 15:04:03.713408 ERROR Error:         result = self.fn(*self.args, **self.kwargs)
2025-06-04 15:04:03.713553 ERROR Error:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-04 15:04:03.713691 ERROR Error:       File "/conf/apps/status_notifier/status_notifier.py", line 12, in initialize
2025-06-04 15:04:03.713809 ERROR Error:         self.global_vars = self.get_app('global_vars')
2025-06-04 15:04:03.713952 ERROR Error:         ^^^^^^^^^^^^^^^^
2025-06-04 15:04:03.714077 ERROR Error: ===========================================================================

```
```
homeassistant:~/app/persistant-data/appdaemon/config/apps# docker ps |grep appda
28fb7c2cb849   acockburn/appdaemon:4.5.8                      "sh -c 'sleep 1 && .…"   4 minutes ago   Up 4 minutes   5050/tcp                                                        appdaemon
```

**Comment by acockburn** [comment]
We think this was fixed in 4.5.8, and have verified that the method is there. Can you retest with 4.5.10 which was just released - thanks!

**Comment by dekiesel** [comment]
```
2025-06-12 10:29:53.200000 ERROR Error: =====  Failed to start 'stat_notifier_mys_2'  =============================
2025-06-12 10:29:53.200163 ERROR Error: AppStartFailure: App 'stat_notifier_mys_2' failed to start
2025-06-12 10:29:53.200584 ERROR Error:   InitializationFail: initialize() method failed for app 'stat_notifier_mys_2'
2025-06-12 10:29:53.201139 ERROR Error:     AttributeError: property 'global_vars' of 'StatusNotifier' object has no setter
2025-06-12 10:29:53.201799 ERROR Error:       File "/usr/local/lib/python3.12/site-packages/appdaemon/app_management.py", line 392, in start_app
2025-06-12 10:29:53.201944 ERROR Error:         await self.initialize_app(app_name)
2025-06-12 10:29:53.202094 ERROR Error:       File "/usr/local/lib/python3.12/site-packages/appdaemon/app_management.py", line 289, in initialize_app
2025-06-12 10:29:53.202249 ERROR Error:         await utils.run_in_executor(self, init_func)
2025-06-12 10:29:53.202382 ERROR Error:       File "/usr/local/lib/python3.12/site-packages/appdaemon/utils.py", line 561, in run_in_executor
2025-06-12 10:29:53.202533 ERROR Error:         return await future
2025-06-12 10:29:53.202681 ERROR Error:                ^^^^^^^^^^^^
2025-06-12 10:29:53.202829 ERROR Error:       File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
2025-06-12 10:29:53.202991 ERROR Error:         result = self.fn(*self.args, **self.kwargs)
2025-06-12 10:29:53.203117 ERROR Error:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 10:29:53.203275 ERROR Error:       File "/conf/apps/status_notifier/status_notifier.py", line 12, in initialize
2025-06-12 10:29:53.203392 ERROR Error:         self.global_vars = self.get_app('global_vars')
2025-06-12 10:29:53.203534 ERROR Error:         ^^^^^^^^^^^^^^^^
2025-06-12 10:29:53.203681 ERROR Error: ===========================================================================
```

```
homeassistant:~# docker ps|grep app
6d82f8e53b64   acockburn/appdaemon:4.5.10                     "sh -c 'sleep 3 && .…"   2 minutes ago   Up 2 minutes   5050/tcp                                                        appdaemon
homeassistant:~#
```
I am still experiencing this issue in 4.5.10. If there is anything else I can do to help debug this please let me know. Thank you for your help!

**Comment by dekiesel** [comment]
Turns out the reason is a naming collision...

appdaemon uses the name `global_vars` internally.

```
appdaemon/appdaemon.py:        self.global_vars: Any = {}
```

So when I initialize my `global_vars` it overwrites/collides with appdaemons.

Simply renaming the var to something like

```
self.global_vars_app = self.get_app('global_vars')
```
Works. Sorry for the confusion!
